name: Push-to-S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: Push-to-S3@main
      with:
        args: --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: s3://aws-lambda-github
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
